name: HearthTune
services:
  api: &api-template
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: hearthtune_server
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    volumes:
      - ./server/src:/app/server/src
      - ./server/storage/music:/app/server/storage/music
      - ./common:/app/common:ro
      - /app/server/node_modules
    depends_on:
      - db

  db: &db-template
    env_file:
      - ./server/.env
    image: mongo:8.0
    container_name: hearthtune_db
    volumes:
      - mongo_data:/data/db
  test-db:
    <<: *db-template
    container_name: hearthtune_test_db
    volumes: []

  test:
    <<: *api-template
    environment:
      - FORCE_COLOR=1
    container_name: hearthtune_test
    volumes:
      - ./server/src:/app/server/src
      - ./common:/app/common/:ro
      - /app/server/storage/music
      - /app/server/node_modules

    ports: []
    command: npm test -- --watchAll
    depends_on:
      - test-db
volumes:
  mongo_data:
  mongo_test_data:
