name: HearthTune
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: hearthtune_server
    ports:
      - "4000:4000"
    volumes:
      - ./server/src:/app/src
      - ./server/.env:/app/.env
      - ./server/storage/music:/app/storage/music
      - /app/node_modules
      - ./server/cookies.txt:/app/cookies.txt:ro
    depends_on:
      - db

  db:
    image: mongo:8.2.3
    container_name: hearthtune_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}

    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
